using System.ComponentModel.DataAnnotations;using Microsoft.AspNetCore.Identity;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.EntityFrameworkCore;using MYOB.Data;using MYOB.Models;using MYOB.Services;using MYOB.Support;
namespace MYOB.Pages.Settings.Users;
public class EditModel(UserManager<ApplicationUser> users,ApplicationDbContext db,IPermissionService permissions,IAuditService audit):PageModel
{
    [BindProperty]public InputModel Input{get;set;}=new();public IReadOnlyList<ScreenDefinition> Screens=>ScreenCatalog.All;
    public sealed class InputModel{public string Id{get;set;}="";[Required]public string FullName{get;set;}="";[Required,EmailAddress]public string Email{get;set;}="";public bool IsAdmin{get;set;}public List<PermissionInput> Permissions{get;set;}=[];}
    public sealed class PermissionInput{public string ScreenKey{get;set;}="";public bool CanView{get;set;}public bool CanAdd{get;set;}public bool CanUpdate{get;set;}public bool CanDelete{get;set;}}
    public async Task<IActionResult> OnGetAsync(string id){if(!await permissions.HasAsync(User,ScreenCatalog.Users,PermissionAction.Update))return Forbid();var user=await users.FindByIdAsync(id);if(user is null)return NotFound();var existing=await db.ScreenPermissions.AsNoTracking().Where(x=>x.UserId==id).ToDictionaryAsync(x=>x.ScreenKey);Input=new(){Id=user.Id,FullName=user.FullName,Email=user.Email??"",IsAdmin=user.IsAdmin,Permissions=ScreenCatalog.All.Select(s=>existing.TryGetValue(s.Key,out var p)?new PermissionInput{ScreenKey=s.Key,CanView=p.CanView,CanAdd=p.CanAdd,CanUpdate=p.CanUpdate,CanDelete=p.CanDelete}:new PermissionInput{ScreenKey=s.Key}).ToList()};return Page();}
    public async Task<IActionResult> OnPostAsync(){if(!await permissions.HasAsync(User,ScreenCatalog.Users,PermissionAction.Update))return Forbid();if(!ModelState.IsValid)return Page();var user=await users.FindByIdAsync(Input.Id);if(user is null)return NotFound();var before=System.Text.Json.JsonSerializer.Serialize(new{user.FullName,user.Email,user.IsAdmin});user.FullName=Input.FullName;user.Email=Input.Email;user.UserName=Input.Email;user.IsAdmin=Input.IsAdmin;var result=await users.UpdateAsync(user);if(!result.Succeeded){foreach(var e in result.Errors)ModelState.AddModelError(string.Empty,e.Description);return Page();}if(Input.IsAdmin&&!await users.IsInRoleAsync(user,"Admin"))await users.AddToRoleAsync(user,"Admin");if(!Input.IsAdmin&&await users.IsInRoleAsync(user,"Admin"))await users.RemoveFromRoleAsync(user,"Admin");var old=await db.ScreenPermissions.Where(x=>x.UserId==user.Id).ToListAsync();db.ScreenPermissions.RemoveRange(old);db.ScreenPermissions.AddRange(Input.Permissions.Select(x=>new ScreenPermission{UserId=user.Id,ScreenKey=x.ScreenKey,CanView=x.CanView,CanAdd=x.CanAdd,CanUpdate=x.CanUpdate,CanDelete=x.CanDelete}));await db.SaveChangesAsync();await audit.WriteAsync(HttpContext,"تعديل","/Settings/Users",entity:"ApplicationUser",recordId:user.Id,oldValues:before,newValues:System.Text.Json.JsonSerializer.Serialize(new{user.FullName,user.Email,user.IsAdmin,Input.Permissions}));TempData["Message"]="تم تحديث المستخدم والصلاحيات";return RedirectToPage("Index");}
}
